---
title: 'Computational modelling of judgments, decisions and cognition -- Materials
author: "Dr. Nico Gradwohl"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r markdown-prep}
library(dplyr)  # basic package for changing data structures.

library(ggplot2)  # important package for plotting.

thlg <- theme(axis.title = element_text(size = 16),
              axis.text = element_text(size = 14),
              legend.title = element_text(size = 14),
              legend.text = element_text(size = 12))
```


# Ressources for data etc. 

* Exercises for book. https://psy-farrell.github.io/computational-modelling//exercises/ 

* Code from book: https://osf.io/ejfm4/files/osfstorage

* Data and code from Tump et al. (2020) https://osf.io/ejfm4/files/osfstorage



# Session 0 

## Example: Task performance 

```{r, fig-forget}

# Forgetting data:
  N <- 150
  t <- 0:N

  # Power:
    Ap <- 1000
    Bp <- 500
    bet <- 0.4
  
    RTp <- Ap + Bp * (t + 1)^(-bet) + rnorm(N + 1, 0, 50)

  # Exponential:
    Ae <- 1000
    Be <- 500
    alp <- 0.6
  
    RTe <- Ae + Be * exp(-alp * t) + rnorm(N + 1, 0, 50)

  # Linear:

# Plotting:
  pow_lin_dat <- data.frame(t = t, RTp = RTp, RTe = RTe,
              pred_p = Ap + Bp * (t + 1)^(-bet),
              pred_e = Ae + Be * exp(-alp * t)) %>%
    ggplot(aes(x = t)) +
    geom_point(aes(y = RTp), size = 3, alpha = 0.5) +
    labs(y = "RT (ms)", linetype = "") +
    geom_line(aes(y = pred_p, linetype = "Power law"), linewidth = 1, color = NA) +
    # geom_line(aes(y = pred_e, linetype = "Exponetial law"), linewidth = 1) +
    # Linear:
    geom_smooth(aes(y = RTp, linetype = "Linear"), method = "lm", se = FALSE, linewidth = 1, color = NA) +
    theme_bw() +
    thlg

  pow_lin_dat

  ggsave("_figures/pow_lin_dat.png", height = 12, width = 16, unit = "cm")


  pow_lin <- pow_lin_dat +
    # geom_line(aes(y = pred_e, linetype = "Exponetial law"), linewidth = 1) +
    # Linear:
    geom_smooth(aes(y = RTp, linetype = "Linear"), method = "lm", se = FALSE, linewidth = 1, color = "black")

  
  pow_lin
  ggsave("_figures/lin.png", height = 12, width = 16, unit = "cm")


  pow_lin +
    geom_line(aes(y = pred_p, linetype = "Power law"), linewidth = 1)

  ggsave("_figures/pow_lin.png", height = 12, width = 16, unit = "cm")

```





## Tax cut 

```{r}
# Average tax cut of $ 1,083 
# 
# But: 80% receive less than this cut, half (around 45 Million people) receive less than $ 100, $ 30,127 for the top 1%

# Try with lognormal:
  curmu <- 0.01
  cursd <- 10000
  
  x <- seq(0, curmu + cursd, by = 0.1)
  plot(x, dlnorm(x, log(curmu), log(cursd)), type = "l")
  
  
  1- plnorm(c(30127), log(curmu), log(cursd))
  plnorm(c(1083, 100), log(curmu), log(cursd))
  
  # Target probabilities:
  c(0.01, 0.8, 0.5)
  
  # Use a pareto distribution:
    # Equations:
    # x_m = 1/(1 - 0.5)^(-1/a) = 100
    # x_m = 1/(1 - 0.8)^(-1/a) = 1083
    # x_m = 1/(1 - 0.01)^(-1/a) = 30127
    # a <- 1083/(1083-x_m)


    x_m <- 200 

    a <- 1083/(1083-x_m)
    
    
    x <- seq(1, 10000, by = 0.2)

    pout <- (a * x_m^a)/(x^(a+1))  # PDF.

    (mpar <- (a * x_m)/(a - 1))
    # To have a mean of 1083 a can be: a = mpar/(mpar - x_m)
    
    (qtpar08 <- x_m * (1 - 0.8)^(-1/a))  # 30127

    (qtpar05 <- x_m * (1 - 0.5)^(-1/a))
    

    data.frame(x = x, y = pout) %>%
      ggplot(aes(x = x, y = y)) +
      geom_line(linewidth = 1) +
      geom_vline(aes(linetype = "mean"), xintercept = mpar) +
      geom_vline(aes(linetype = "mean"), xintercept = mpar) +
      scale_x_continuous(trans = "log10") +
      thlg +
      theme_bw()
  

```



## Linear model 

```{r lin-rel}
# Simple linear relationship:
  n <- 100
  set.seed(09234)
  learn_speed <- rnorm(n)
  alcohol <- rnorm(n, learn_speed)  # assuming that more intelligent people drink more  
```


```{r lin-dat}

  plt_alc_learn <- data.frame(alcohol = alcohol, learn_speed = learn_speed) %>%
    ggplot(aes(x = alcohol, y = learn_speed)) +
    geom_point(size = 3) +
    labs(x = "Alcohol Consumption", y = "Learn Speed", linetype = "") +
    theme_bw() +
    thlg

# Show and save:
plt_alc_learn

ggsave("_figures/alc_learn_raw.png", height = 12, width = 12, unit = "cm")
```


```{r mean-mod}
plt_alc_learn +
    geom_hline(yintercept = mean(learn_speed), linewidth = 1)

ggsave("_figures/alc_learn_mean.png", height = 12, width = 12, unit = "cm")
```


```{r lin-mod-simple}
  plt_alc_learn +
      # Linear:
      geom_abline(slope = 1, linewidth = 1) +
      annotate(geom = "polygon", x = c(1, 0, 1), y = c(1, 0, 0),
              linetype = "dashed", color = "black",
              alpha = 0.3)
  
  ggsave("_figures/alc_learn_lm.png", height = 12, width = 12, unit = "cm")


# Fitted model:
  fit <- lm(learn_speed ~ alcohol)
  summary(fit)

  ic <- coef(fit)["(Intercept)"]   # intercept.
  slp <- coef(fit)["alcohol"]

plt_alc_learn +
    # Linear:
    geom_smooth(method = "lm", se = FALSE, linewidth = 1, color = "black") +
    geom_abline(intercept = ic, slope = slp, linewidth = 1) +
    annotate(geom = "polygon", x = c(1, 0, 1), y = c(1, 0, 0) * slp + ic,
            linetype = "dashed", color = "black",
            alpha = 0.3) +
    annotate(geom = "text", x = 1, y = slp/2 + ic, label = round(slp, 2), size = 6, hjust = 0)

ggsave("_figures/alc_learn_fit.png", height = 12, width = 12, unit = "cm")
```



# Session 1 

## Mass vs. Density 

```{r mass-dens}
n_correct <- 0:10
pvals <- dbinom(n_correct, size = 10, prob = .75)
pmass <- data.frame(n_correct = factor(n_correct), pn = pvals) %>%
  ggplot(aes(x = n_correct, y = pn)) +
  geom_col() +
  # scale_x_binned(n.breaks = 11, show.limits = TRUE, right = FALSE) +
  theme_classic()

pmass
ggsave("_figures/pmass.png", height = 12, width = 12, unit = "cm")

pmass +
  annotate(geom = "segment", 
           x = 8, y = 0, yend = pvals[n_correct == 7], linetype = "dashed", linewidth = 1) +
  annotate(geom = "segment", 
           x = 0, xend = 8, y = pvals[n_correct == 7], linetype = "dashed", linewidth = 1) +
  annotate(geom = "point", x = 8, y = pvals[n_correct == 7], size = 3)

ggsave("_figures/pmass_lik.png", height = 12, width = 12, unit = "cm")

# Density:
tr <- seq(0, 30, by = 0.01)
dvals <- dlnorm(tr, 2, 1.7)
pdens <- data.frame(t = tr, dens = dvals) %>%
  ggplot(aes(x = tr, y = dens)) +
  geom_line(linewidth = 1) +
  theme_classic()

pdens
ggsave("_figures/pdens.png", height = 12, width = 12, unit = "cm")

pdens +
  annotate(geom = "segment", 
           x = 7, y = 0, yend = dvals[tr == 7], linetype = "dashed", linewidth = 1) +
  annotate(geom = "segment", 
           x = 0, xend = 7, y = dvals[tr == 7], linetype = "dashed", linewidth = 1) +
  annotate(geom = "point", x = 7, y = dvals[tr == 7], size = 3)
ggsave("_figures/pdens_lik.png", height = 12, width = 12, unit = "cm")
```



## Visualize Prospect Theory 

Value function 

```{r valfun}
# Define function:
value_function <- function(x, alp, bet = alp, lamb){
  ifelse(x >= 0, x^alp, -lamb * (-x)^bet)
}


# Visualize:
  x <- seq(-100, 100, by = 1)  # define values.


# Create combinations of different parameters:
  dm <- expand.grid(alp = c(0.1, 0.5, 0.8), lambda = c(1, 2))

# Get data for each combination:
  outlist <- apply(dm, MARGIN = 1, FUN = function(rw){
    data.frame(x = x, V = value_function(x, alp = rw[1], lamb = rw[2]), alp = rw[1], lamb = rw[2]) 
  })

  outdat <- do.call(rbind, outlist)  # combine the list into a single data.frame.

outdat %>%
  ggplot(aes(x = x, y = V, color = alp, linetype = factor(lamb), group = interaction(lamb, alp))) +
  geom_line(linewidth = 1) +
  scale_color_distiller(palette = "Spectral") +
  theme_classic()

ggsave("_figures/valfun.png", height = 12, width = 12, unit = "cm")
```


## Visualize MAB 

```{r generate-pdat}
probdat <- seq(0.05, 0.95, by = 0.15)  # probabilities.

# FUnction to generate rewards:
curprob <- probdat[1]  # selecting a probability.

tr <- 200  # 200 rounds.
rbinom(tr, 1, curprob)  # get an outcome according to a bernoulli distribution.

# Simple Q-learning:-----------------
  get_cmat <- function(choice, input){
    
    # Input matrix with row and column indices and values:
    inp <- as.matrix(cbind(1:length(choice), choice, input))
    
    # Get own rewards for each choice:
    cmat <- matrix(0, ncol = 2, nrow = length(choice)) 
    cmat[inp[,1:2]] <- inp[, 3]
    
    return(cmat)
    
  }

  # Utility function:
  utpay <- function(rew, choice) {
  
    # Input matrix with row and column indices and values:
    paymat <- get_cmat(choice = choice, input = rew)
    
    return(paymat)

  }

update_q <- function(qprev,  # vector of previous q values
                     ut,  # vector of rewards / utilities.
                     alp,  # alpha
                     update_unchosen = TRUE,
                     choices = NA
)  {
  
  
  pred_err <- ut - qprev  # prediction error.
  
  # Should the unchosen option be updated?
  if(!update_unchosen){
    # Set prediction error == 0 for unchosen option:
    pred_err[3 - choices] <- 0
      # Note: Replace 2 by length(options) for more than 2 options.
      # Alternatively: Update the unchosen and rewarded option with 1? 
    # ut[cbind(1:3, choices + 1)]  # rewards from chosen.
    
  }
  
  qnew <- qprev + alp * pred_err
  
  return(qnew)
  
}


  simfun <- function(theta, competition = TRUE, op_prob = c(0.5, 0.5),
                       utfun = utpay, nind = 3, maxtr = 200, maxrew = 1){
      
      ## 4.1 Get parameters:  
      lpar <- theta[1]  # get corresponding learning parameter phi/alpha.
      soft <- theta[length(theta)]  # softmax parameter is always last in list!.
      
      # For mimicking Schulze et al., the softmax paramter is transformed
      # (we use soft instead of c to avoid collision):
      
      soft <- 3^(10 * soft) - 1  
      
      # First round: -------------------------------------------------------
      # Choices (rows are rounds, columns individuals):
      cmat <- matrix(sample(c(0, 1), size = nind, prob = c(0.5, 0.5), replace = TRUE),
                     nrow = 1)
      
      # Rewards (rows are rounds, columns individuals):
      rew_choice <- sample(c(0, 1), size = 1,
                           prob = op_prob)
      rmat <- ifelse(rew_choice == cmat & any(rew_choice == cmat),  
                      # if any chose the rewarded option for all.
                     competition * maxrew/sum(rew_choice == cmat) +
                       (1 - competition) * maxrew,  # maximum reward distributed.  
                     0)
      
      # utfun(rew = rmat[1, ], choice = cmat[1,])
      utmat <- array(rep(0, 2 * nind * maxtr), dim = c(nind, 2, maxtr))  # utility matrix in given round.
      # Individuals are rows, opotions are columns.
      
      utmat[, rew_choice + 1, 1] <- rmat  # add rewarded option.
      # TODO: Translate utuitlity if necessary.
      utmat[,,1:2]
      
      
      ## 3.3 Initialize option value matrix:
      optval_mat <- array(rep(NA, 2 * nind * maxtr), dim = c(nind, 2, maxtr))   # option values for each choice
      optval_mat[,,1] <- 0
      
      
      
    # 4.2 Loop over subsequent trials: ---------------------------------
      for(tr in 2:maxtr) {
    
    
        # Learning:
        ## 4.2.1 Get data from previous trial:
        choices <- cmat[tr - 1,]  # choices in previous round.
        pi_cur <- utmat[, , tr - 1]  # get utilities from previous trial.
    
        ## 4.2.2 Update learned values:
    
        # Which formulation is used?
        # TODO: Probably this is actually obsolete as both functions are essentially the same!
    
        # a) A learning rule:
        # Matrix of option values in current round:
        optval_mat_tr <- update_q(qprev = optval_mat[,,tr - 1],
                                  ut = pi_cur,
                                  alp = lpar)
    
        if(is.null(dim(optval_mat_tr))){
          dim(optval_mat_tr) <- c(nind, 2)
        }
    
        # Save option value matrix:
        optval_mat[,,tr] <- optval_mat_tr  # get a matrix of q-values.
    
        # Choices:
        # subtraction of each row's maximum to avoid overflow problems.
        optval_mat_tr <- t(apply(optval_mat_tr, MAR = 1, function(x) x - max(x)))
    
        # Adapted from Charley:
        p <- exp(optval_mat_tr * soft)  # Softmax rule.
        # TODO: Use division or multiplication?
    
        p <- p/rowSums(p)  # get probabilities for each option.
    
        # Get a choice for each individual:
        # sample(matrix(rep(c(0, 1), each = nind), ncol = 2), size = nind, replace = TRUE, prob = p)
    
        cvec <- apply(p, MARGIN = 1, FUN = function(p){
          sample(c(0, 1), size = 1, prob = p)
        })
    
        cmat <- rbind(cmat, cvec)
    
        # Rewards:
        # Rewards (rows are rounds, columns individuals):
        rew_choice <- sample(c(0, 1), size = 1, prob = op_prob)
        rmat <- ifelse(rew_choice == cvec & any(rew_choice == cvec),  # if any chose the rewarded option for all.
                       competition * maxrew/sum(rew_choice == cvec) +
                         (1 - competition) * maxrew/2,  
                          # maximum reward distributed (divide by 2 for non-competition).
                       0)
    
    
        utmat[, rew_choice + 1, tr] <- rmat  # add rewarded option.
        # TODO: Translate utuitlity if necessary.
    
      }  # eof. loop.
    
      return(list(cmat = cmat, optval = optval_mat))
    
    }
```

```{r run-sims}
theta_cur <- 0.1

dm <- expand.grid(theta_cur = c(0.2, 0.8),
                  p = c(0.2, 0.5, 0.9))

outlist <- lapply(1:nrow(dm), FUN = function(rw){
  simout <- simfun(theta = c(0.9, dm$theta_cur[rw]), nind = 1, op_prob = c(dm$p[rw], 1-dm$p[rw]))

  soft <- 3^(10 * dm$theta_cur[rw]) - 1  

  optval_mat_tr <- t(apply(simout$optval[1,,], MAR = 2, function(x) x - max(x)))
  oprobs <- exp(optval_mat_tr * soft)
  data.frame(tr = 1:length(simout$cmat), p = dm$p[rw], theta = dm$theta_cur[rw],
        oval = simout$optval[,2,], oprob = (oprobs/rowSums(oprobs))[,2], 
        choice = simout$cmat)
})


do.call(rbind, outlist) %>%
  ggplot(aes(x = tr, y = oprob, color = factor(p))) +
  facet_grid(theta ~ p, labeller = label_both) +
  geom_line(linewidth = 0.5, alpha = 0.7) +
  geom_point(aes(y = choice), position = position_jitter(height = 0.01)) +
  scale_color_brewer(palette = "Dark2") +
  theme_bw() +
  theme(legend.position = "bottom")

ggsave("_figures/rl_example.png", height = 16, width = 24, unit = "cm")
```


# Session 2

## [TODO] Illustrate Grid search 


## [TODO] Illustrate Nelder-mead -- Simplex 



## [TODO] Simulations 
