---
title: 'Computational modelling of judgments, decisions and cognition -- Assignments 2: Getting started'
author: "[YOUR NAME]"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r markdown-prep}
library(dplyr)  # basic package for changing data structures.

library(ggplot2)  # important package for plotting.
```


# General rules for handing in assignments 


1. You have to hand in all assignments except for one ungraded assignment.

1. Upload your assignments to ilias until Wednesday 3 pm. 

1. Assignments are *not* graded, unless it says so in the beginning of the assignment. 

1. You have to complete all numbered tasks; if there are one or more bonus tasks, you may skip them 



# Modelling Gamble Data

In this Assignment you will model gamble data.
You will receive pick one (or more) of the suggested models, visualize their functions, receive code to simulate an environment and simulate choice data for the set of simulated gambles and output the result.


# Model suggestions  

All gambles consist of a probability, $p_i$ being the probability of (monetary) outcome $x_i$ and $k$ being the number of outcomes in the gamble.

## Expected value (EV) 

\[
EV = \sum_{i=1}^k p_i x_i
\]


## Expected utility (EU) 

\[
EV = \sum_{i=1}^k p_i x_i^{\alpha}
\]

with $\alpha < 1$ representing diminishing marginal utility (additional money having less value than the previous dollar).



## Prospect theory 

The values and probabilities of a gamble are transformed and used as a basis for decision making.

The subjective value $V(A)$ of gamble A consists of the sum of decisions weights $\pi_i$ times outcomes passed through a function $v(x_i)$ with $v(0) = 0$ [e.g., @GloecknerPachur12]

\[
V(A) = \sum_{i=1}^k \pi_i v(x_i)
\]

Functions differ for positive and negative outcomes.
You can decide if you want to focus on the gain-domain (positive outcomes) by filtering the inputs ("gambles").


I suggest the following functions (You can look for your own functions in the literature): 

Probability weighting function:

Probabilities are weighted by:

 \[\pi(p_i) = \frac{p_i^c}{[p_i^c + (1 - p_i^c)]^{1/c}}\] 
 
with $c = \gamma$ for gains and $c = \delta$ for losses. For simplicity I suggest to assume that $\gamma = \delta < 1$.



Value functions:

\[
\begin{array}{rcl}
v(x) = x^{\alpha} & \mbox{for} & x \geq 0 \\ 
v(x) = -\lambda(-x)^\beta & \mbox{for} & x < 0 \\
\end{array}
\]

For simplicity I suggest to assume that $\alpha = \beta < 1$ and maybe even $\lambda = 1$ (i.e., no stronger weighting of losses resulting in *loss aversion*).


### Cumulative Prospect Theory 

If you want a challenge, you can also try to fit Cumulative Prospect Theory:

To make it cumulative prospect theory. This uses a rank-dependent weighting scheme: 

A gamble has *positive* outcomes $x_m > \ldots > x_1 \geq 0$ and *negative* outcomes $0 > y_1 > \ldots > y_n$ with corresponding probabilities $p_m \ldots p_1$ and $q_1 \ldots q_n$.

\[
\begin{array}{c}
\pi_m^+ = w^+(p_m) \\
\pi_m^- = w^-(q_n) \\
\pi_i^+ = w^+(p_i + \ldots + p_m) - w^+(p_{i+1} + \ldots + p_m) \\
\pi_i^- = w^-(q_j + \ldots + q_n) - w^+(q_{i+1} + \ldots + p_n) \\
\end{array}
\]

and 

\[
w^+ = \frac{\delta^+ p^{\gamma^+}}{\delta^+ p^{\gamma^+} + (1 - p)^{\gamma^+}}
\]

\[
w^- = \frac{\delta^- p^{\gamma^-}}{\delta^- p^{\gamma^-} - (1 - p)^{\gamma^-}}
\]


If you use this function you may simplify things and assume $\delta^+ = \delta^- = 1$ and/or $\gamma^+ = \gamma^-$.
$\gamma$ and $\delta$ separate curvature and elevation of the function.



## Simulating choices 

If you want to simulate choices you can use a softmax rule: 

\[p(A) = \frac{e^{\phi v(A)}}{e^{\phi v(A)} + e^{\phi v(B)}}\]

with $\phi$ indicating how noisy the responding is, with smaller $\phi$ being related to more random responding (inverse temperature parameter). 







# Task 1: Visualizing functions

Visualize the function(s) in the model you use to describe the choice data.


# Task 2: Understanding the Environment

Set your own seed, run the generation of the environment and understand the gamble environment 


# Task 3: Simulating Data

1. Simulate data from about hundred individuals with different parameters.

1. Visualize the value (and probability) judgments and choice probabilities 

1. Obtain the corresponding choice data 



# Task 4: Learn about Bayesian Statistics

Watch the first 9 videos of the following youtube playlist (it is okay, if you don't watch all unti next session):
https://youtube.com/playlist?list=PLFDbGp5YzjqXQ4oE4w9GVWdiokWB9gEpm&si=emFyWAjPCWcwEFs6


# Task 5 (optional) 

Pick another model and or environment and simulate data from this. 